apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: data
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
  my.cnf: |
    # mysql configuration file
    [mysqld]

    log-bin
    binlog_format = row
    gtid-mode = on
    enforce-gtid-consistency = on
    log-slave-updates

    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: Service
metadata:
  namespace: data
  name: mysql-service
spec:
  ports:
  - name: mysql-service
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: data
  name: mysql-read-service
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306