---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-local-storage
  namespace: data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: data
  name: mysql-pv-0
  labels:
    type: local
spec:
  storageClassName: mysql-local-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: data
  name: mysql-pv-1
  labels:
    type: local
spec:
  storageClassName: mysql-local-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"